/** German fallback labels for Features mega menu when i18n keys are missing. */
export const FEATURES_MENU_FALLBACK_DE: Record<string, unknown> = {
  title: "Features",
  close: "Features-Menü schließen",
  categories: {
    create: "CREATE",
    visuals: "VISUALS",
    video: "VIDEO",
    avatar: "AVATAR & AUDIO",
    intelligence: "INTELLIGENCE",
    workflow: "WORKFLOW",
  },
  groups: {
    scripts: { title: "Scripts & Hooks" },
    ads: { title: "Werbung & Ads" },
    images: { title: "Bilder & Avatare" },
    ugc: { title: "UGC & Commerce" },
    motion: { title: "Motion & Clips" },
    edit: { title: "Edit & Transform" },
    live: { title: "Live & Charaktere" },
    audio: { title: "Audio & Sync" },
    agent: { title: "Agent & Kampagnen" },
    analysis: { title: "Analyse & Score" },
    library: { title: "Archiv" },
    tools: { title: "Insights" },
  },
  items: {
    script: "Script Generator",
    hook: "Viral Hook Generator",
    trend: "Trend Script",
    calendar: "Content Kalender",
    product: "Produkt-Werbung",
    ad: "Ad Creator",
    thumbnail: "Thumbnail Konzept",
    imageGen: "Bild Generator",
    kiIch: "Mein KI-Ich",
    lora: "LoRA Training",
    upscaler: "HD Upscaler",
    ugcVideo: "UGC Video",
    ecommerce: "E-Commerce Ads",
    story: "Story Creator",
    scene: "Szenen Generator",
    seedance: "Video Motion",
    textToVideo: "Text to Video",
    transform: "Video Transformer",
    remix: "Video Remix",
    motionTransfer: "Motion Transfer",
    liveCreator: "Live Creator",
    avatarStudio: "Avatar Studio",
    character: "Character Studio",
    lipsync: "Lipsync Studio",
    melodia: "Melodia Studio",
    translate: "Video Übersetzer",
    faceStudio: "Face Studio",
    autopilot: "Agent Autopilot",
    campaign: "Campaign Autopilot",
    score: "Viral Score",
    outlier: "Outlier Detector",
    niche: "Niche Analyzer",
    competitor: "Konkurrenz-Analyse",
    gallery: "Studio Archiv",
    analytics: "Analytics",
  },
  promo: {
    campaign: {
      label: "AI Campaign Studio",
      headline: "Aus einer Idee wird eine Kampagne.",
      description: "Bilder, Motion, Hooks und Score — in einem Workflow.",
      cta: "Jetzt starten",
      href: "/auth/sign-up",
    },
    create: {
      label: "Content Create",
      headline: "Scripts die sofort postbar sind.",
      description: "Hooks, Kalender und Ads aus einem Briefing.",
      cta: "Script erstellen",
      href: "/dashboard/script-generator",
    },
    visuals: {
      label: "VISUAL STUDIO",
      headline: "Brand Assets in Sekunden.",
      description: "KI-Bilder, Avatare und UGC-Look für Social.",
      cta: "Bild generieren",
      href: "/dashboard/image-generator",
    },
    video: {
      label: "Video Motion",
      headline: "Bild wird Motion Clip.",
      description: "Story, Szenen und Video-Transformation.",
      cta: "Video starten",
      href: "/dashboard/story-creator",
    },
    avatar: {
      label: "Avatar Studio",
      headline: "Dein KI-Gesicht. Überall konsistent.",
      description: "Live, Lipsync und Stimme in einem Flow.",
      cta: "Live Creator öffnen",
      href: "/dashboard/live-creator",
    },
    intelligence: {
      label: "Creative Intelligence",
      headline: "Datenbasiert statt raten.",
      description: "Agent, Score und Wettbewerbs-Analyse.",
      cta: "Agent Autopilot",
      href: "/dashboard/ki-agent",
    },
  },
};
