/**
 * canonical-tools-data.ts
 *
 * Production tool entries for the canonical registry.
 * Values sourced from code audit (Phase 1A) — not guessed.
 * Unclear values marked DOCS_REQUIRED.
 */

import type { CanonicalToolDefinition } from "./canonical-tool-types";

// ─── Helpers (registry authoring only) ───────────────────────────────────────

function nav(
  id: string,
  label: string,
  page: string | null,
  notes: string
): CanonicalToolDefinition {
  return {
    id,
    label,
    description: notes,
    category: "nav",
    provider: "none",
    model: "none",
    route: null,
    page,
    status: "active",
    isProduction: true,
    requiresPlan: false,
    requiresConsent: false,
    consentType: "none",
    inputTypes: [],
    outputTypes: [],
    uiOptions: [],
    creditPolicy: {
      mode: "none",
      displayedCredits: 0,
      baseCredits: 0,
      chargeTiming: "none",
      refundPolicy: "not_needed",
      runtimeSource: "registry",
    },
    knownMismatches: [],
    docsRequired: false,
    notes,
  };
}

// ─── Production tools ────────────────────────────────────────────────────────

export const PRODUCTION_CANONICAL_TOOLS: CanonicalToolDefinition[] = [
  // ── Navigation ────────────────────────────────────────────────────────────
  nav("studio", "Studio", "/dashboard", "Dashboard home / StudioCommandCenter. No generation API."),
  nav("gallery", "Galerie", "/dashboard/gallery", "Asset archive. Triggers copilot on gallery view."),
  nav("settings", "Einstellungen", "/dashboard/settings", "Split: SettingsView inline + legacy settings page."),

  // ── Text tools ────────────────────────────────────────────────────────────
  {
    id: "viral-hook",
    label: "Viral Hook",
    description: "Scroll-stoppende Hooks aus Thema/Kontext.",
    category: "text",
    provider: "Anthropic",
    model: "claude",
    route: "/api/viral-hook",
    page: "/dashboard/viral-hook",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["prompt", "topic"],
    outputTypes: ["text"],
    uiOptions: ["topic", "platform", "language"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 1,
      baseCredits: 1,
      variants: [
        { key: "api", label: "API /api/viral-hook", credits: 1, condition: "VIRAL_HOOK_EXTRACTOR_CREDIT_COST" },
        { key: "dashboard-page", label: "Dashboard viral-hook page", credits: "DOCS_REQUIRED", condition: "May use VIRAL_HOOK_CREDIT_COST=3 separately" },
      ],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["Dashboard page may charge 3 via VIRAL_HOOK_CREDIT_COST while API uses 1"],
    docsRequired: true,
    notes: "AgentBox TEXT_TOOLS shows 1. Dedicated route uses withCreditDeduction.",
    aliases: ["viral_hook"],
  },
  {
    id: "content-calendar",
    label: "Content Kalender",
    description: "7-Tage-Content-Plan aus Briefing.",
    category: "text",
    provider: "Anthropic",
    model: "claude",
    route: "/api/content-kalender",
    page: "/dashboard/content-kalender",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["topic", "brief"],
    outputTypes: ["text", "pdf"],
    uiOptions: ["topic", "platforms"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 2,
      baseCredits: 2,
      variants: [
        { key: "api-route", label: "/api/content-kalender", credits: 2, condition: "CONTENT_KALENDER_TOOL_CREDIT_COST" },
        { key: "server-action", label: "generateContentCalendar action", credits: 5, condition: "Post-pay server action" },
        { key: "agent-orchestrator", label: "/api/agent path", credits: "dynamic", condition: "ORCHESTRATOR_BASE_COST=1 + tool cost" },
      ],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI calculateExactCredits=2; server action=5; AgentBox via /api/agent may differ"],
    docsRequired: false,
    notes: "Three billing paths documented in audit.",
    aliases: ["content_kalender", "content-calendar"],
  },
  {
    id: "trend-script",
    label: "Trend Script",
    description: "Script aus Trend-Videos (YouTube + Claude).",
    category: "text",
    provider: "multiple",
    model: "claude",
    route: "/api/trend-script",
    page: "/dashboard/trend-to-script",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["topic", "niche", "platform"],
    outputTypes: ["text"],
    uiOptions: ["niche", "platform", "language", "duration"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 3,
      baseCredits: 3,
      variants: [
        { key: "api", label: "TREND_SCRIPT_TOOL_CREDIT_COST", credits: 3 },
        { key: "campaign-estimate", label: "sumCampaignPlanCredits", credits: 4, condition: "Campaign planner overestimate" },
      ],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "legacy_constant",
    },
    knownMismatches: ["Campaign sumCampaignPlanCredits uses 4 for trend-script"],
    docsRequired: false,
    notes: "promptOptimizer correctly returns 3.",
    aliases: ["trend_script"],
  },
  {
    id: "script-generator",
    label: "Script Generator",
    description: "YouTube-Shorts-Skripte mit Hook/Story/CTA.",
    category: "text",
    provider: "Anthropic",
    model: "claude",
    route: null,
    page: "/dashboard/script-generator",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["topic"],
    outputTypes: ["text"],
    uiOptions: ["topic", "hook", "duration", "language"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 2,
      baseCredits: 2,
      variants: [{ key: "agent", label: "AGENT_TOOL_CREDITS.generate_script", credits: 2 }],
      chargeTiming: "postpay",
      refundPolicy: "missing",
      runtimeSource: "api_route",
    },
    knownMismatches: ["Post-pay via server action generateScript — provider cost before debit"],
    docsRequired: false,
    notes: "Master Agent executable tool.",
    aliases: ["script_generator"],
  },

  // ── Image tools ───────────────────────────────────────────────────────────
  {
    id: "image-gen",
    label: "Bildgenerator",
    description: "Text-zu-Bild (Krea / Flux via fal.ai).",
    category: "image",
    provider: "fal.ai",
    model: "catalog",
    route: "/api/generate-image",
    page: "/dashboard/image-generator",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["prompt"],
    outputTypes: ["image"],
    uiOptions: ["aspectRatio", "highRes", "modelId", "category", "variation", "platform"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 3,
      baseCredits: 5,
      variants: [
        { key: "standard", label: "IMAGE_GEN_CREDITS.standard / fluxDev", credits: 5 },
        { key: "highRes", label: "IMAGE_GEN_CREDITS.highRes / fluxProT2i", credits: 8 },
        { key: "variation", label: "variation mode", credits: 5 },
        { key: "ui-default", label: "calculateExactCredits default", credits: 3, condition: "nano-banana-2 default in AgentBox" },
      ],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI AgentBox shows 3 default; API charges 5/8. SettingsPanel lists nano-banana models not in API whitelist"],
    docsRequired: true,
    notes: "tool-registry bild-generator uses flux models with credits 5/8.",
    aliases: ["bild-generator", "image_generator", "flux-image"],
  },
  {
    id: "img-to-img",
    label: "Bild zu Bild",
    description: "Bild-Variation via /api/generate-image variation:true.",
    category: "image",
    provider: "fal.ai",
    model: "catalog",
    route: "/api/generate-image",
    page: null,
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["prompt", "image"],
    outputTypes: ["image"],
    uiOptions: ["variation", "aspectRatio"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 3,
      baseCredits: 5,
      variants: [{ key: "api-variation", label: "variation:true", credits: 5 }],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI shows 3; API variation charges 5 (fluxDev)"],
    docsRequired: false,
    notes: "AgentBox media tool only.",
  },
  {
    id: "ki-ich",
    label: "Mein KI-Ich",
    description: "Portrait in Szenen via Flux PuLID.",
    category: "avatar",
    provider: "fal.ai",
    model: "fal-ai/flux-pulid",
    route: "/api/ki-ich",
    page: "/dashboard/ki-influencer",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: true,
    consentType: "avatar_from_face",
    inputTypes: ["image", "scene"],
    outputTypes: ["image"],
    uiOptions: ["mode:preview|final", "scene"],
    creditPolicy: {
      mode: "free_preview",
      displayedCredits: "DOCS_REQUIRED",
      baseCredits: 8,
      variants: [
        { key: "preview", label: "preview mode", credits: 0 },
        { key: "final", label: "FAL_CREDITS.fluxPulid", credits: 8 },
      ],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["Preview mode free without documented rate limit"],
    docsRequired: true,
    notes: "assertGatedFeature ki-ich. Alias ki_ich, ki-influencer.",
    aliases: ["ki_ich", "ki-influencer"],
  },
  {
    id: "lora-training",
    label: "LoRA Training",
    description: "Custom LoRA train + generate via fal.ai.",
    category: "image",
    provider: "fal.ai",
    model: "fal-ai/flux-lora-portrait-trainer",
    route: "/api/lora/train",
    page: "/dashboard/lora-training",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: true,
    consentType: "lora_training",
    inputTypes: ["images_zip", "trigger_word"],
    outputTypes: ["lora_weights"],
    uiOptions: ["steps", "triggerWord", "type"],
    creditPolicy: {
      mode: "per_step",
      displayedCredits: "dynamic",
      baseCredits: 5,
      variants: [
        { key: "train", label: "calcLoraCredits(steps)", credits: "dynamic", condition: "5 + 5 per 1000 steps" },
        { key: "generate", label: "/api/lora/generate", credits: 2 },
      ],
      chargeTiming: "postpay",
      refundPolicy: "manual_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["POST-PAY RISK: fal submit before deductCredits in /api/lora/train"],
    docsRequired: true,
    notes: "High priority credit hardening candidate.",
    aliases: ["lora_training"],
  },
  {
    id: "upscale",
    label: "Upscaler",
    description: "Bild-Upscale via fal clarity-upscaler.",
    category: "image",
    provider: "fal.ai",
    model: "fal-ai/clarity-upscaler",
    route: "/api/upscale",
    page: "/dashboard/upscaler",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["image", "generationId"],
    outputTypes: ["image"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 4,
      baseCredits: 4,
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "legacy_constant",
    },
    knownMismatches: [],
    docsRequired: true,
    notes: "FAL_CREDITS.clarityUpscaler=4.",
  },

  // ── Video — Akool / fal ───────────────────────────────────────────────────
  {
    id: "szenen-generator",
    label: "Szenen Generator",
    description: "Image-to-video studio with Akool model catalog.",
    category: "video",
    provider: "multiple",
    model: "catalog",
    route: "/api/akool/image-to-video",
    page: "/dashboard/szenen-generator",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["image", "prompt"],
    outputTypes: ["video"],
    uiOptions: ["modelId", "duration", "resolution", "aspectRatio", "audioMode", "cinematic", "reference", "lastFrame"],
    creditPolicy: {
      mode: "dynamic",
      displayedCredits: "dynamic",
      baseCredits: null,
      variants: [
        { key: "api", label: "calculateAkoolModelCredits", credits: "dynamic", condition: "round(unit_credit × duration)" },
        { key: "tool-registry-stale", label: "tool-registry.ts model credits", credits: 900, condition: "STALE placeholder 900/1100/800 — not billing truth" },
        { key: "ui-agentbox", label: "calculateExactCredits img-to-video", credits: 15, condition: "duration<10 else 30 — flat wrong" },
      ],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "provider_dynamic",
    },
    knownMismatches: ["tool-registry.ts shows 900–1100 credits; runtime uses Akool API unit_credit×duration", "AgentBox flat 15/30 vs dynamic API"],
    docsRequired: true,
    notes: "Canonical page for img-to-video sidebar redirect.",
    aliases: ["img-to-video"],
  },
  {
    id: "text-to-video",
    label: "Text zu Video",
    description: "Akool text2video generation.",
    category: "video",
    provider: "Akool",
    model: "catalog",
    route: "/api/akool/text-to-video",
    page: null,
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["prompt"],
    outputTypes: ["video"],
    uiOptions: ["modelId", "duration", "resolution"],
    creditPolicy: {
      mode: "dynamic",
      displayedCredits: 10,
      baseCredits: null,
      variants: [
        { key: "dynamic", label: "calculateAkoolModelCredits", credits: "dynamic" },
        { key: "fallback", label: "AKOOL_TOOL_CREDITS.textToVideo", credits: 50 },
        { key: "ui-akool-flat", label: "calculateExactCredits AKOOL_TOOLS", credits: 10 },
        { key: "ui-duration", label: "calculateExactCredits duration branch", credits: 15, condition: "5s; 30 if >=10s" },
      ],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "provider_dynamic",
    },
    knownMismatches: ["UI flat 10 (AKOOL_TOOLS) vs dynamic API; fallback 50 when model unknown"],
    docsRequired: true,
    notes: "AgentBox media tool.",
  },
  {
    id: "video-to-video",
    label: "Video to Video",
    description: "Akool style-transfer (video editor).",
    category: "video",
    provider: "Akool",
    model: "DOCS_REQUIRED",
    route: "/api/akool/video-to-video",
    page: "/dashboard/video-editor",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["video"],
    outputTypes: ["video"],
    uiOptions: ["style"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 15,
      baseCredits: 40,
      variants: [{ key: "api", label: "AKOOL_TOOL_CREDITS.videoEditor", credits: 40 }],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI calculateExactCredits=15; API AKOOL_TOOL_CREDITS.videoEditor=40"],
    docsRequired: true,
    notes: "Same route as ai-video-editor.",
    aliases: ["ai-video-editor"],
  },
  {
    id: "ecommerce-ads",
    label: "E-Commerce Product Ads",
    description: "Akool product-ad image generation.",
    category: "video",
    provider: "Akool",
    model: "DOCS_REQUIRED",
    route: "/api/akool/ecommerce-ads",
    page: null,
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["product", "prompt"],
    outputTypes: ["image"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 8,
      baseCredits: 15,
      variants: [{ key: "api", label: "AKOOL_TOOL_CREDITS.ecommerceAds", credits: 15 }],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI calculateExactCredits=8; API=15"],
    docsRequired: true,
    notes: "AgentBox media tool with right panel.",
  },
  {
    id: "seedance",
    label: "Seedance (legacy page)",
    description: "Akool image2video via /api/seedance.",
    category: "video",
    provider: "Akool",
    model: "catalog",
    route: "/api/seedance",
    page: "/dashboard/seedance",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["image", "prompt"],
    outputTypes: ["video"],
    uiOptions: ["modelId", "duration", "resolution", "lastFrameUrl"],
    creditPolicy: {
      mode: "dynamic",
      displayedCredits: "dynamic",
      baseCredits: null,
      variants: [
        { key: "api", label: "calculateAkoolModelCredits via seedance-generate", credits: "dynamic" },
        { key: "config-label", label: "SEEDANCE_CREDIT_COST / FAL_CREDITS.seedanceVideo", credits: 40, condition: "Config label only; actual Akool dynamic" },
      ],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "provider_dynamic",
    },
    knownMismatches: ["FAL_CREDITS.seedanceVideo=40 is label; billing is Akool dynamic"],
    docsRequired: true,
    notes: "Parallel to szenen-generator; prefer szenen-generator as canonical UI.",
  },
  {
    id: "story-creator",
    label: "Story Creator",
    description: "Text-to-video via Akool.",
    category: "video",
    provider: "Akool",
    model: "akool-t2v-fast",
    route: "/api/akool/text-to-video",
    page: "/dashboard/story-creator",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["prompt"],
    outputTypes: ["video"],
    uiOptions: ["duration", "resolution", "aspectRatio", "style", "cameraMotion"],
    creditPolicy: {
      mode: "dynamic",
      displayedCredits: 30,
      baseCredits: 30,
      variants: [
        { key: "tool-registry", label: "tool-registry story-creator base", credits: 30 },
        { key: "api", label: "Akool dynamic", credits: "dynamic" },
      ],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "provider_dynamic",
    },
    knownMismatches: ["tool-registry shows static 30; API may differ per model"],
    docsRequired: true,
    notes: "4-tool studio registry entry.",
  },
  {
    id: "product-ad",
    label: "Produkt-Werbung",
    description: "Kling product video ad via fal.ai.",
    category: "video",
    provider: "fal.ai",
    model: "fal-ai/kling-video/v1.6/pro/image-to-video",
    route: "/api/product-ad/generate",
    page: "/dashboard/produkt",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["image", "productName", "script"],
    outputTypes: ["video"],
    uiOptions: ["batch", "upscale", "language", "style", "platform", "audience"],
    creditPolicy: {
      mode: "batch",
      displayedCredits: 75,
      baseCredits: 75,
      variants: [
        { key: "standard", label: "PRODUCT_AD_CREDITS standard", credits: 75 },
        { key: "batch", label: "batch mode", credits: 225, condition: "3× standard" },
      ],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: [],
    docsRequired: true,
    notes: "assertGatedFeature produkt-ads. Alias produkt_werbung.",
    aliases: ["produkt_werbung", "produkt-werbung"],
  },
  {
    id: "motion-transfer",
    label: "Motion Transfer",
    description: "Kling v3 motion-control.",
    category: "video",
    provider: "fal.ai",
    model: "fal-ai/kling-video/v3/pro/motion-control",
    route: "/api/motion-transfer",
    page: "/dashboard/motion-transfer",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: true,
    consentType: "none",
    inputTypes: ["image", "video"],
    outputTypes: ["video"],
    uiOptions: ["sourceIsVideo"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 8,
      baseCredits: 8,
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "legacy_constant",
    },
    knownMismatches: [],
    docsRequired: true,
    notes: "MOTION_TRANSFER_CREDIT_COST=8.",
    aliases: ["motion_transfer"],
  },
  {
    id: "talking-avatar",
    label: "Sprechender Avatar (Lip Sync)",
    description: "Akool lipsync video+audio.",
    category: "video",
    provider: "Akool",
    model: "DOCS_REQUIRED",
    route: "/api/akool/lipsync",
    page: "/dashboard/lipsync-studio",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["video", "audio"],
    outputTypes: ["video"],
    uiOptions: ["voiceId", "ttsText"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 10,
      baseCredits: 20,
      variants: [{ key: "api", label: "AKOOL_TOOL_CREDITS.lipsync", credits: 20 }],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI AKOOL_TOOLS flat 10; API lipsync=20"],
    docsRequired: true,
    notes: "No consent gate on API route (audit finding).",
    aliases: ["lipsync-studio"],
  },
  {
    id: "talking-photo",
    label: "Sprechendes Foto",
    description: "fal.ai live-portrait.",
    category: "video",
    provider: "fal.ai",
    model: "fal-ai/live-portrait",
    route: "/api/live-portrait",
    page: "/dashboard/live-portrait",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: true,
    consentType: "avatar_from_face",
    inputTypes: ["image", "drivingVideo"],
    outputTypes: ["video"],
    uiOptions: ["webcam|upload"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 10,
      baseCredits: 5,
      variants: [
        { key: "route", label: "/api/live-portrait hardcoded", credits: 5 },
        { key: "config", label: "FAL_CREDITS.liveCreatorPortrait", credits: 20, condition: "portrait-frame route uses 20" },
      ],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI AKOOL flat 10; route=5; live-creator portrait-frame=20", "Returns raw CDN URL — no asset ingest"],
    docsRequired: true,
    notes: "Consent required in UI.",
  },
  {
    id: "face-swap",
    label: "Gesichtstausch",
    description: "Akool face swap image or video.",
    category: "avatar",
    provider: "Akool",
    model: "DOCS_REQUIRED",
    route: "/api/faceswap",
    page: "/dashboard/face-studio",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: true,
    consentType: "face_swap",
    inputTypes: ["source", "target"],
    outputTypes: ["image", "video"],
    uiOptions: ["mode:image|video"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 10,
      baseCredits: 5,
      variants: [
        { key: "image", label: "CREDIT_IMAGE", credits: 5 },
        { key: "video", label: "CREDIT_VIDEO", credits: 10 },
      ],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI AKOOL_TOOLS flat 10 for all face tools"],
    docsRequired: true,
    notes: "Consolidates face-swap-video, face-swap-image, live-face-swap.",
    aliases: ["face-swap-video", "face-swap-image", "live-face-swap", "face_swap"],
  },
  {
    id: "character-studio",
    label: "Character Studio",
    description: "Akool character swap.",
    category: "video",
    provider: "Akool",
    model: "DOCS_REQUIRED",
    route: "/api/akool/character-studio",
    page: "/dashboard/character-studio",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["video"],
    outputTypes: ["video"],
    uiOptions: ["mode:animate|replace"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 10,
      baseCredits: 25,
      variants: [{ key: "api", label: "AKOOL_TOOL_CREDITS.characterStudio", credits: 25 }],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI AKOOL flat 10; API=25"],
    docsRequired: true,
    notes: "Aliases char-studio-video, character-swap, char-studio-image.",
    aliases: ["char-studio-video", "character-swap", "char-studio-image"],
  },
  {
    id: "video-translation",
    label: "Videoübersetzung",
    description: "Akool video translation.",
    category: "video",
    provider: "Akool",
    model: "DOCS_REQUIRED",
    route: "/api/akool/video-translation",
    page: "/dashboard/video-translation",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["video", "durationMinutes"],
    outputTypes: ["video"],
    uiOptions: ["durationMinutes"],
    creditPolicy: {
      mode: "per_minute",
      displayedCredits: 10,
      baseCredits: 30,
      variants: [{ key: "api", label: "minutes × AKOOL_TOOL_CREDITS.videoTranslationPerMinute", credits: "dynamic" }],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI flat 10; API 30/min"],
    docsRequired: true,
    notes: "Duplicate page /dashboard/video-uebersetzer.",
  },
  {
    id: "avatar-video",
    label: "Avatar Video",
    description: "Avatar render pipeline (create-job + start-render).",
    category: "video",
    provider: "Akool",
    model: "DOCS_REQUIRED",
    route: "/api/avatar/create-job",
    page: "/dashboard/avatar-studio",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["image", "video", "options"],
    outputTypes: ["video"],
    uiOptions: ["DOCS_REQUIRED"],
    creditPolicy: {
      mode: "dynamic",
      displayedCredits: 10,
      baseCredits: null,
      variants: [{ key: "estimate", label: "estimateAvatarCredits", credits: "dynamic", condition: "Basis 5/9/16 + addons 5–21" }],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI flat 10"],
    docsRequired: true,
    notes: "Pre-pay with refund on failure.",
  },
  {
    id: "ugc-video",
    label: "UGC Video",
    description: "Talking avatar UGC ads.",
    category: "video",
    provider: "multiple",
    model: "DOCS_REQUIRED",
    route: "/api/ugc-video",
    page: "/dashboard/ugc-video",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: true,
    consentType: "avatar_from_face",
    inputTypes: ["avatarId", "script", "customPhoto"],
    outputTypes: ["video"],
    uiOptions: ["voiceSource:akool|elevenlabs", "voiceId", "aspectRatio:9:16"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 5,
      baseCredits: 5,
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["ElevenLabs TTS sidecar not separately billed"],
    docsRequired: true,
    notes: "UGC_VIDEO_CREDIT_COST=5.",
    aliases: ["ugc_video"],
  },
  {
    id: "live-creator",
    label: "Live Creator",
    description: "Talking photo + realtime FlashHead studio.",
    category: "avatar",
    provider: "multiple",
    model: "fal-ai/flashhead",
    route: "/api/live-creator",
    page: "/dashboard/live-creator",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: true,
    consentType: "live_creator",
    inputTypes: ["photo", "script", "audio"],
    outputTypes: ["video", "stream"],
    uiOptions: ["voiceSource", "realtimeToken"],
    creditPolicy: {
      mode: "deferred",
      displayedCredits: 10,
      baseCredits: 10,
      variants: [
        { key: "talking-photo-complete", label: "GET poll completion", credits: 10 },
        { key: "heartbeat", label: "LIVE_CREATOR_CREDITS_PER_MINUTE", credits: 2, condition: "per minute via heartbeat" },
        { key: "portrait-frame", label: "LIVE_CREATOR_PORTRAIT_CREDIT_COST", credits: 20 },
      ],
      chargeTiming: "deferred",
      refundPolicy: "missing",
      runtimeSource: "api_route",
    },
    knownMismatches: ["POST starts Akool job without deduct; GET deducts on complete", "POST only hasEnoughCredits check"],
    docsRequired: true,
    notes: "DEFERRED BILLING RISK.",
    aliases: ["live_creator"],
  },
  {
    id: "live-avatar",
    label: "Live Avatar Session",
    description: "Akool/Agora streaming avatar.",
    category: "live",
    provider: "Akool",
    model: "DOCS_REQUIRED",
    route: "/api/live-avatar/session",
    page: null,
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["avatarId", "durationSec"],
    outputTypes: ["stream"],
    uiOptions: [],
    creditPolicy: {
      mode: "per_minute",
      displayedCredits: "dynamic",
      baseCredits: 1,
      variants: [{ key: "session", label: "LIVE_AVATAR_CREDITS_PER_MINUTE", credits: 1, condition: "per minute + heartbeat" }],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["No dashboard UI (sidebar removed v10)"],
    docsRequired: true,
    notes: "API complete; UI missing. Aliases live-camera, streaming-avatar.",
    aliases: ["live-camera", "streaming-avatar"],
  },

  // ── Audio ─────────────────────────────────────────────────────────────────
  {
    id: "melodia-tts",
    label: "Melodia Studio (TTS)",
    description: "Akool text-to-speech.",
    category: "audio",
    provider: "Akool",
    model: "DOCS_REQUIRED",
    route: "/api/akool/tts",
    page: "/dashboard/melodia",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["text", "voiceId"],
    outputTypes: ["audio"],
    uiOptions: ["voiceId"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 2,
      baseCredits: 3,
      variants: [{ key: "api", label: "AKOOL_TOOL_CREDITS.tts", credits: 3 }],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI calculateExactCredits tts=2; API=3"],
    docsRequired: true,
    notes: "Alias tts.",
    aliases: ["tts"],
  },
  {
    id: "voice-clone-akool",
    label: "Stimmenklon (Akool)",
    description: "Akool voice clone.",
    category: "audio",
    provider: "Akool",
    model: "DOCS_REQUIRED",
    route: "/api/akool/voice-clone",
    page: "/dashboard/melodia",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: true,
    consentType: "voice_clone",
    inputTypes: ["audio"],
    outputTypes: ["voiceId"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 2,
      baseCredits: 5,
      variants: [{ key: "api", label: "AKOOL_TOOL_CREDITS.voiceClone", credits: 5 }],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI=2; API=5"],
    docsRequired: true,
    notes: "Tab on melodia page. Alias voice-clone.",
    aliases: ["voice-clone"],
  },
  {
    id: "voice-changer",
    label: "Stimmverzerrer",
    description: "Akool voice change.",
    category: "audio",
    provider: "Akool",
    model: "DOCS_REQUIRED",
    route: "/api/akool/voice-changer",
    page: "/dashboard/melodia",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["audio"],
    outputTypes: ["audio"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 2,
      baseCredits: 5,
      variants: [{ key: "api", label: "AKOOL_TOOL_CREDITS.voiceChanger", credits: 5 }],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["UI=2; API=5"],
    docsRequired: true,
    notes: "Tab on melodia page.",
  },
  {
    id: "stimme-speak",
    label: "Stimme & Musik (ElevenLabs TTS)",
    description: "ElevenLabs TTS via /api/stimme/speak.",
    category: "audio",
    provider: "ElevenLabs",
    model: "eleven_multilingual_v2",
    route: "/api/stimme/speak",
    page: "/dashboard/stimme-musik",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: true,
    consentType: "voice_clone",
    inputTypes: ["text", "voiceId"],
    outputTypes: ["audio"],
    uiOptions: ["voiceId"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: "DOCS_REQUIRED",
      baseCredits: 2,
      chargeTiming: "postpay",
      refundPolicy: "missing",
      runtimeSource: "api_route",
    },
    knownMismatches: ["POST-PAY: ElevenLabs called before deductCredits"],
    docsRequired: true,
    notes: "assertGatedFeature voice-clone.",
    aliases: ["stimme_musik"],
  },
  {
    id: "stimme-clone",
    label: "Stimme klonen (ElevenLabs)",
    description: "ElevenLabs voice add.",
    category: "audio",
    provider: "ElevenLabs",
    model: "DOCS_REQUIRED",
    route: "/api/stimme/clone",
    page: "/dashboard/stimme-musik",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: true,
    consentType: "voice_clone",
    inputTypes: ["audio", "name"],
    outputTypes: ["voiceId"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: "DOCS_REQUIRED",
      baseCredits: 2,
      chargeTiming: "postpay",
      refundPolicy: "missing",
      runtimeSource: "api_route",
    },
    knownMismatches: ["POST-PAY after ElevenLabs /v1/voices/add"],
    docsRequired: true,
    notes: "Separate from Akool voice-clone path.",
  },
  {
    id: "elevenlabs-voice-preview",
    label: "ElevenLabs Voice Preview",
    description: "Unmetered voice preview endpoint.",
    category: "api_route",
    provider: "ElevenLabs",
    model: "eleven_multilingual_v2",
    route: "/api/elevenlabs/voice-preview",
    page: null,
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["voiceId", "text"],
    outputTypes: ["audio"],
    uiOptions: ["voiceId", "text"],
    creditPolicy: {
      mode: "none",
      displayedCredits: 0,
      baseCredits: 0,
      chargeTiming: "none",
      refundPolicy: "not_needed",
      runtimeSource: "api_route",
    },
    knownMismatches: ["Unmetered preview — abuse risk"],
    docsRequired: true,
    notes: "Used by UGC video voice preview.",
  },

  // ── Analysis ──────────────────────────────────────────────────────────────
  {
    id: "viral-score",
    label: "Viral Score",
    description: "Content viral potential score.",
    category: "analysis",
    provider: "Anthropic",
    model: "claude",
    route: "/api/viral-score",
    page: "/dashboard/viral-score",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["content"],
    outputTypes: ["json"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 2,
      baseCredits: 2,
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "legacy_constant",
    },
    knownMismatches: [],
    docsRequired: false,
    notes: "VIRAL_SCORE_CREDIT_COST=2.",
    aliases: ["viral_score"],
  },
  {
    id: "niche-analyzer",
    label: "Niche Analyzer",
    description: "Niche analysis via Claude.",
    category: "analysis",
    provider: "Anthropic",
    model: "claude",
    route: "/api/niche-analyzer",
    page: "/dashboard/niche-analyzer",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["niche"],
    outputTypes: ["text"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 2,
      baseCredits: 2,
      chargeTiming: "postpay",
      refundPolicy: "missing",
      runtimeSource: "api_route",
    },
    knownMismatches: ["POST-PAY via analyzeNiche server action"],
    docsRequired: false,
    notes: "Agent tool analyze_niche.",
    aliases: ["niche_analyzer"],
  },
  {
    id: "outlier-detector",
    label: "Outlier Detector",
    description: "Outlier content detection.",
    category: "analysis",
    provider: "Anthropic",
    model: "claude",
    route: "/api/outlier-detector",
    page: "/dashboard/outlier-detector",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["content"],
    outputTypes: ["text"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 3,
      baseCredits: 3,
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["E2E mock still deducts credits"],
    docsRequired: false,
    notes: "detect_outliers agent tool.",
    aliases: ["outlier_detector"],
  },
  {
    id: "competitor",
    label: "Competitor Analyse",
    description: "YouTube competitor analysis.",
    category: "analysis",
    provider: "multiple",
    model: "claude",
    route: "/api/competitor",
    page: "/dashboard/competitor",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["channel"],
    outputTypes: ["text"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 5,
      baseCredits: 5,
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "legacy_constant",
    },
    knownMismatches: [],
    docsRequired: false,
    notes: "COMPETITOR_ANALYSIS_CREDIT_COST=5.",
  },
  {
    id: "thumbnail-concept",
    label: "Thumbnail Konzept",
    description: "Thumbnail concept generation.",
    category: "image",
    provider: "Anthropic",
    model: "claude",
    route: null,
    page: "/dashboard/thumbnail-concept",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["topic"],
    outputTypes: ["text"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 1,
      baseCredits: 1,
      chargeTiming: "postpay",
      refundPolicy: "missing",
      runtimeSource: "api_route",
    },
    knownMismatches: ["POST-PAY server action"],
    docsRequired: false,
    notes: "generate_thumbnail agent tool.",
    aliases: ["thumbnail_concept"],
  },

  // ── Agent / Automation ────────────────────────────────────────────────────
  {
    id: "agent-autopilot",
    label: "Agent Autopilot",
    description: "KI Agent chat orchestration.",
    category: "automation",
    provider: "Anthropic",
    model: "claude-sonnet-4-5",
    route: "/api/agent",
    page: "/dashboard/ki-agent/chat",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["prompt", "conversation"],
    outputTypes: ["mixed"],
    uiOptions: ["mode:agent|campaign"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 1,
      baseCredits: 1,
      variants: [
        { key: "base", label: "ORCHESTRATOR_BASE_COST", credits: 1 },
        { key: "tool-registry", label: "tool-registry agent-autopilot", credits: 5, condition: "STALE UI label" },
        { key: "per-tool", label: "executable tools", credits: "dynamic" },
      ],
      chargeTiming: "prepay",
      refundPolicy: "auto_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["tool-registry.ts credits.base=5 vs ORCHESTRATOR_BASE_COST=1", "AgentBox text tools show 1–3 but bill via /api/agent at 1"],
    docsRequired: false,
    notes: "Landing /dashboard/ki-agent → chat.",
    aliases: ["agent-autopilot", "ki_agent_fallback"],
  },
  {
    id: "agent-copilot",
    label: "Agent Copilot",
    description: "Lightweight Q&A + tool navigation.",
    category: "api_route",
    provider: "Anthropic",
    model: "claude",
    route: "/api/agent/copilot",
    page: null,
    status: "active",
    isProduction: true,
    requiresPlan: false,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["message"],
    outputTypes: ["text"],
    uiOptions: [],
    creditPolicy: {
      mode: "none",
      displayedCredits: 0,
      baseCredits: 0,
      chargeTiming: "none",
      refundPolicy: "not_needed",
      runtimeSource: "api_route",
    },
    knownMismatches: ["NO PLAN OR CREDIT GATE — free LLM abuse risk", "Copilot system prompt lists wrong tool prices"],
    docsRequired: false,
    notes: "Used by StudioCommandCenter CopilotChat.",
  },
  {
    id: "agent-stream-tool",
    label: "Agent Stream Tool",
    description: "Tool output streaming without billing.",
    category: "api_route",
    provider: "none",
    model: "none",
    route: "/api/agent/stream-tool",
    page: null,
    status: "active",
    isProduction: true,
    requiresPlan: false,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["tool", "payload"],
    outputTypes: ["stream"],
    uiOptions: [],
    creditPolicy: {
      mode: "none",
      displayedCredits: 0,
      baseCredits: 0,
      chargeTiming: "none",
      refundPolicy: "not_needed",
      runtimeSource: "unknown",
    },
    knownMismatches: ["Auth only — billing elsewhere undocumented"],
    docsRequired: false,
    notes: "Credit hardening candidate.",
  },
  {
    id: "campaign-autopilot",
    label: "Campaign Autopilot",
    description: "Multi-step campaign from brief.",
    category: "campaign",
    provider: "Anthropic",
    model: "claude",
    route: "/api/agent/campaign",
    page: "/dashboard/campaign-autopilot",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["brief"],
    outputTypes: ["mixed"],
    uiOptions: [],
    creditPolicy: {
      mode: "dynamic",
      displayedCredits: "dynamic",
      baseCredits: null,
      variants: [
        { key: "lump", label: "sumCampaignPlanCredits upfront", credits: "dynamic" },
        { key: "range", label: "agent registry estimate", credits: "dynamic", condition: "20–300 documented" },
      ],
      chargeTiming: "prepay",
      refundPolicy: "no_refund",
      runtimeSource: "api_route",
    },
    knownMismatches: ["sumCampaignPlanCredits overcharges vs actual tool costs", "No refund if steps fail"],
    docsRequired: true,
    notes: "campaign_autopilot agent registry entry.",
    aliases: ["campaign_autopilot"],
  },

  // ── API v1 (public) ─────────────────────────────────────────────────────
  {
    id: "api-v1-image",
    label: "API v1 Image",
    description: "Public API image generation.",
    category: "api_route",
    provider: "fal.ai",
    model: "catalog",
    route: "/api/v1/image",
    page: "/dashboard/api",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["prompt"],
    outputTypes: ["image"],
    uiOptions: ["aspect_ratio", "high_res"],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 5,
      baseCredits: 5,
      variants: [{ key: "cost", label: "API_CREDIT_COSTS.image", credits: 5 }],
      chargeTiming: "postpay",
      refundPolicy: "missing",
      runtimeSource: "api_route",
    },
    knownMismatches: ["POST-PAY withCredits — provider cost if deduct fails"],
    docsRequired: true,
    notes: "Bearer API key auth.",
  },
  {
    id: "api-v1-script",
    label: "API v1 Script",
    description: "Public API script generation.",
    category: "api_route",
    provider: "Anthropic",
    model: "claude",
    route: "/api/v1/script",
    page: "/dashboard/api",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["topic"],
    outputTypes: ["text"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 2,
      baseCredits: 2,
      chargeTiming: "postpay",
      refundPolicy: "missing",
      runtimeSource: "api_route",
    },
    knownMismatches: ["POST-PAY pattern"],
    docsRequired: false,
    notes: "API_CREDIT_COSTS.script=2.",
  },
  {
    id: "api-v1-niche",
    label: "API v1 Niche",
    description: "Public API niche analysis.",
    category: "api_route",
    provider: "Anthropic",
    model: "claude",
    route: "/api/v1/niche",
    page: "/dashboard/api",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["niche"],
    outputTypes: ["text"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 2,
      baseCredits: 2,
      chargeTiming: "postpay",
      refundPolicy: "missing",
      runtimeSource: "api_route",
    },
    knownMismatches: ["POST-PAY pattern"],
    docsRequired: false,
    notes: "API_CREDIT_COSTS.niche=2.",
  },
  {
    id: "api-v1-outlier",
    label: "API v1 Outlier",
    description: "Public API outlier detection.",
    category: "api_route",
    provider: "Anthropic",
    model: "claude",
    route: "/api/v1/outlier",
    page: "/dashboard/api",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["content"],
    outputTypes: ["text"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 3,
      baseCredits: 3,
      chargeTiming: "postpay",
      refundPolicy: "missing",
      runtimeSource: "api_route",
    },
    knownMismatches: ["POST-PAY pattern"],
    docsRequired: false,
    notes: "API_CREDIT_COSTS.outlier=3.",
  },
  {
    id: "api-v1-thumbnail",
    label: "API v1 Thumbnail",
    description: "Public API thumbnail concept.",
    category: "api_route",
    provider: "Anthropic",
    model: "claude",
    route: "/api/v1/thumbnail",
    page: "/dashboard/api",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["topic"],
    outputTypes: ["text"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 1,
      baseCredits: 1,
      chargeTiming: "postpay",
      refundPolicy: "missing",
      runtimeSource: "api_route",
    },
    knownMismatches: ["POST-PAY pattern"],
    docsRequired: false,
    notes: "API_CREDIT_COSTS.thumbnail=1.",
  },
  {
    id: "api-v1-viral-score",
    label: "API v1 Viral Score",
    description: "Public API viral score.",
    category: "api_route",
    provider: "Anthropic",
    model: "claude",
    route: "/api/v1/viral-score",
    page: "/dashboard/api",
    status: "active",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["content"],
    outputTypes: ["json"],
    uiOptions: [],
    creditPolicy: {
      mode: "fixed",
      displayedCredits: 2,
      baseCredits: 2,
      chargeTiming: "postpay",
      refundPolicy: "missing",
      runtimeSource: "api_route",
    },
    knownMismatches: ["POST-PAY pattern"],
    docsRequired: false,
    notes: "API_CREDIT_COSTS.viralScore.",
  },

  // ── Coming soon (production ids, no API) ─────────────────────────────────
  {
    id: "ref-to-video",
    label: "Reference to Video",
    description: "Reference-driven video — not implemented.",
    category: "video",
    provider: "none",
    model: "none",
    route: null,
    page: null,
    status: "coming-soon",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: ["reference"],
    outputTypes: ["video"],
    uiOptions: [],
    creditPolicy: {
      mode: "unknown",
      displayedCredits: 15,
      baseCredits: null,
      chargeTiming: "unknown",
      refundPolicy: "missing",
      runtimeSource: "ui_estimate",
    },
    knownMismatches: ["AgentBox mock may deduct credits for placeholder", "UI shows 15 — no API"],
    docsRequired: true,
    notes: "Still in ToolId union and copilot prompt.",
  },
  {
    id: "jarvis-moderator",
    label: "Jarvis Moderator",
    description: "Content moderation — not implemented.",
    category: "live",
    provider: "none",
    model: "none",
    route: null,
    page: null,
    status: "coming-soon",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: [],
    outputTypes: [],
    uiOptions: [],
    creditPolicy: {
      mode: "unknown",
      displayedCredits: 1,
      baseCredits: null,
      chargeTiming: "unknown",
      refundPolicy: "missing",
      runtimeSource: "ui_estimate",
    },
    knownMismatches: [],
    docsRequired: true,
    notes: "Removed from sidebar.",
  },
  {
    id: "ai-support-agent",
    label: "KI-Support-Mitarbeiter",
    description: "AI support agent — not implemented.",
    category: "live",
    provider: "none",
    model: "none",
    route: null,
    page: null,
    status: "coming-soon",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: [],
    outputTypes: [],
    uiOptions: [],
    creditPolicy: {
      mode: "unknown",
      displayedCredits: 10,
      baseCredits: null,
      chargeTiming: "unknown",
      refundPolicy: "missing",
      runtimeSource: "ui_estimate",
    },
    knownMismatches: [],
    docsRequired: true,
    notes: "Removed from sidebar.",
  },
  {
    id: "akool-production",
    label: "Akool Production",
    description: "Akool production feature — not implemented.",
    category: "live",
    provider: "none",
    model: "none",
    route: null,
    page: null,
    status: "coming-soon",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: [],
    outputTypes: [],
    uiOptions: [],
    creditPolicy: {
      mode: "unknown",
      displayedCredits: 10,
      baseCredits: null,
      chargeTiming: "unknown",
      refundPolicy: "missing",
      runtimeSource: "ui_estimate",
    },
    knownMismatches: [],
    docsRequired: true,
    notes: "Removed from sidebar.",
  },
  {
    id: "holographic-avatar",
    label: "Holografische Avatar-Anzeige",
    description: "Holographic avatar — not implemented.",
    category: "live",
    provider: "none",
    model: "none",
    route: null,
    page: null,
    status: "coming-soon",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: [],
    outputTypes: [],
    uiOptions: [],
    creditPolicy: {
      mode: "unknown",
      displayedCredits: 10,
      baseCredits: null,
      chargeTiming: "unknown",
      refundPolicy: "missing",
      runtimeSource: "ui_estimate",
    },
    knownMismatches: [],
    docsRequired: true,
    notes: "Removed from sidebar.",
  },
  {
    id: "akool-edge",
    label: "Akool Edge",
    description: "Akool Edge — not implemented.",
    category: "live",
    provider: "none",
    model: "none",
    route: null,
    page: null,
    status: "coming-soon",
    isProduction: true,
    requiresPlan: true,
    requiresConsent: false,
    consentType: "none",
    inputTypes: [],
    outputTypes: [],
    uiOptions: [],
    creditPolicy: {
      mode: "unknown",
      displayedCredits: 10,
      baseCredits: null,
      chargeTiming: "unknown",
      refundPolicy: "missing",
      runtimeSource: "ui_estimate",
    },
    knownMismatches: [],
    docsRequired: true,
    notes: "Removed from sidebar.",
  },
];
