/** German source strings for landing page sections (Sections.tsx). */
export const landingPageDe = {
  ticker: {
    i0: "InfluexAI LiveSwap™",
    i1: "InfluexAI Vision",
    i2: "InfluexAI Avatar Engine",
    i3: "InfluexAI Voice",
    i4: "InfluexAI Music",
    i5: "InfluexAI Brain",
    i6: "InfluexAI Video Engine",
    i7: "InfluexAI Image Engine",
    i8: "Made in Germany",
    i9: "DSGVO-konform",
    i10: "Face Consistency™",
    i11: "Multi-Platform Export",
  },
  brands: {
    kicker: "Für Unternehmen & Marken",
    headline1: "Dein KI-",
    headline2: "Markenbotschafter.",
    headline3: "Immer konsistent.",
    intro:
      "Schluss mit teuren Shootings. InfluexAI gibt deiner Marke einen unverwechselbaren KI-Sprecher der überall gleich aussieht.",
    feat1_title: "Konsistente Markenidentität",
    feat1_desc:
      "Dein KI-Botschafter sieht auf TikTok, Instagram und YouTube identisch aus. Face Consistency über alle Plattformen.",
    feat2_title: "Produktvideos in 90 Sekunden",
    feat2_desc:
      "URL oder Produktfoto eingeben → KI erstellt Script, Stimme und Video. A/B-Varianten automatisch.",
    feat3_title: "Multi-Plattform auf Knopfdruck",
    feat3_desc:
      "TikTok, Instagram, YouTube, LinkedIn — alle Formate in einem Schritt inklusive KI-Hashtags.",
    ex1_cat: "Beauty Brand",
    ex1_title: "Produkt-Kampagne",
    ex1_sub: "URL → 5 TikTok-Ads · 3 Min.",
    ex2_cat: "E-Commerce",
    ex2_title: "Produktfoto KI",
    ex2_sub: "InfluexAI Image Engine",
    ex3_cat: "Tech Company",
    ex3_title: "KI-Sprecher Video",
    ex3_sub: "InfluexAI Avatar Engine",
  },
  features: {
    kicker: "Alle Module",
    headline1: "Vier Flows.",
    headline2: "Ein Studio.",
    sidebar: "Kein Tool-Chaos. Alles für KI-Content in einer Plattform.",
    f1_title: "Live Creator",
    f1_desc:
      "Live streamen ohne dein Gesicht. Echtzeit-Face-Swap auf TikTok, YouTube und Instagram Live.",
    f1_api0: "Echtzeit",
    f1_api1: "Face Consistent",
    f1_api2: "Multi-Platform",
    f2_title: "Mein KI-Ich",
    f2_desc:
      "InfluexAI Vision setzt dich in jede Szene der Welt. Face Consistency über alle generierten Inhalte.",
    f2_api0: "4K Output",
    f2_api1: "Face Consistent",
    f2_api2: "Sofort",
    f3_title: "Produkt-Werbung",
    f3_desc:
      "URL oder Produktfoto → InfluexAI Brain analysiert → Video-Ad in TikTok, Reel und YouTube. A/B-Varianten automatisch.",
    f3_api0: "URL-to-Video",
    f3_api1: "A/B Varianten",
    f3_api2: "Multi-Format",
    f4_title: "Stimme & Musik",
    f4_desc:
      "Stimme klonen in 60 Sekunden. Lizenzfreie Hintergrundmusik und Soundeffekte für jeden Content-Typ.",
    f4_api0: "30+ Sprachen",
    f4_api1: "Lizenzfrei",
    f4_api2: "60 Sek. Klonung",
  },
  how: {
    kicker: "So funktioniert's",
    headline1: "In 3 Schritten",
    headline2: "zum Content.",
    s1_title: "Account erstellen",
    s1_desc: "Account erstellen. Credits ab €4,99 — sofort loslegen.",
    s2_title: "Modul wählen",
    s2_desc:
      "Live Creator, KI-Ich, Produkt-Werbung oder Stimme & Musik — alles in einem Studio.",
    s3_title: "Content generieren",
    s3_desc:
      "Upload, URL oder Text eingeben. KI liefert in Sekunden — exportfertig für alle Plattformen.",
  },
  testimonials: {
    kicker: "Stimmen",
    headline1: "Creator & Marken",
    headline2: "lieben InfluexAI.",
    t1_quote: "Produkt-Ads in unter 3 Minuten. Unser ROAS ist um 40% gestiegen.",
    t1_name: "Lisa M.",
    t1_role: "E-Commerce Creator",
    t2_quote: "Endlich ein Tool wo mein KI-Gesicht überall gleich aussieht.",
    t2_name: "Tom K.",
    t2_role: "TikTok Creator · 280k",
    t3_quote: "Wir sparen 15.000€ pro Monat an Agentur-Kosten.",
    t3_name: "Sarah B.",
    t3_role: "Marketing Lead, D2C Brand",
  },
  faq: {
    kicker: "FAQ",
    headline: "Häufige Fragen",
    q1: "Was sind Credits?",
    a1: "Credits sind die Währung in InfluexAI. Jedes Modul kostet 2–5 Credits pro Generierung. Credits verfallen nicht.",
    q2: "Brauche ich eine Kreditkarte?",
    a2: "Nein. Du kaufst Credits einmalig ab €4,99 — kein Abo, keine versteckten Kosten.",
    q3: "Ist InfluexAI DSGVO-konform?",
    a3: "Ja. Server in der EU, keine Weitergabe deiner Daten an Dritte ohne Einwilligung.",
    q4: "Kann ich meine eigene Stimme klonen?",
    a4: "Ja — im Modul Stimme & Musik. 30+ Sekunden Audio reichen für eine hochwertige Klonung.",
    q5: "Welche Plattformen werden unterstützt?",
    a5: "TikTok, Instagram Reels, YouTube Shorts & Long-Form, LinkedIn — alle gängigen Formate.",
  },
  pricing: {
    kicker: "Preise",
    headline: "Transparent. Skalierbar.",
    monthly: "Monatlich",
    yearly: "Jährlich",
    yearly_discount: "−25%",
    popular: "★ Beliebtester Plan",
    per_month: "/Monat",
    footnote: "Credits verfallen nicht.",
    extra_credits: "Extra-Credits",
    extra_credits_suffix: "ab €5/50 Credits.",
    starter_name: "Agency Starter",
    starter_credits: "50 Credits",
    starter_desc: "Einmaliger Einstieg — Credits sofort verfügbar.",
    starter_cta: "Jetzt starten",
    starter_f1: "Script Generator",
    starter_f2: "Niche Analyzer",
    starter_f3: "Outlier Detector",
    starter_m1: "Video Remix",
    starter_m2: "KI-Ich Pro",
    creator_name: "Pro",
    creator_credits: "500 Credits/Monat",
    creator_desc: "Für Creator und Freelancer.",
    creator_cta: "Pro werden",
    creator_f1: "Live Creator (unlimitiert)",
    creator_f2: "KI-Ich: 100 Bilder + Videos",
    creator_f3: "50 Produkt-Ads",
    creator_f4: "Stimmen-Klonung",
    creator_f5: "Musik-Studio",
    business_name: "Agency Pro",
    business_credits: "2.500 Credits/Monat",
    business_desc: "Für Marken, KMUs und Agenturen.",
    business_cta: "Business starten",
    business_f1: "Alles aus Creator",
    business_f2: "10 Team-Charaktere",
    business_f3: "Brand-Konsistenz-Tools",
    business_f4: "White-Label Export",
    business_f5: "API + Priority Support",
  },
  cta: {
    kicker: "Jetzt starten",
    headline1: "Kein Gesicht.",
    headline2: "Kein Limit.",
    headline3: "Kein Warten.",
    sub1: "Für Creator die viral gehen wollen.",
    sub2: "Für Marken die skalieren möchten.",
    primary: "→ Jetzt starten — ab €4,99",
    secondary: "Für Marken →",
    note: "Credits ab €4,99 · Kein Abo · DSGVO-konform",
  },
  footer_cols: {
    product: "Produkt",
    company: "Unternehmen",
    legal: "Rechtliches",
    product_features: "Features",
    product_pricing: "Preise",
    product_changelog: "Changelog",
    product_api: "API",
    company_about: "Über uns",
    company_blog: "Blog",
    company_careers: "Karriere",
    company_press: "Presse",
    legal_imprint: "Impressum",
    legal_privacy: "Datenschutz",
    legal_terms: "AGB",
    legal_cookies: "Cookies",
  },
};
